version: 0.0.1
services:
  nginx: 
    image: pillar-server
    restart: always
    ports:
      - 6300:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"

  