version: "2"
services:
  nginx: 
    image: "nginx:latest"
    restart: always
    ports:
      - 6300:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  redis:
    image: redis
    ports:
      - "6379:6379"
  mysql:
    container_name: mysql
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_USER: "mytest"
      MYSQL_PASS: "12345678"
    ports:
        - "3307:3306"
    volumes: 
      - ./mysql/:/etc/mysql/

  